spring.application.name=nexora-api

# Carga el fichero .env de la raiz del proyecto como si fueran properties.
# "optional:" = si no existe, no peta (en produccion se usan variables de entorno reales).
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/nexora?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=nexora_user
spring.datasource.password=Nexora123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
